/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarTokenRouteImport } from './routes/validar.$token'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChecklistsIndexRouteImport } from './routes/_authenticated/checklists.index'
import { Route as AuthenticatedChecklistsIdRouteImport } from './routes/_authenticated/checklists.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarTokenRoute = ValidarTokenRouteImport.update({
  id: '/validar/$token',
  path: '/validar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistsIndexRoute =
  AuthenticatedChecklistsIndexRouteImport.update({
    id: '/checklists/',
    path: '/checklists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistsIdRoute =
  AuthenticatedChecklistsIdRouteImport.update({
    id: '/checklists/$id',
    path: '/checklists/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/checklists/': typeof AuthenticatedChecklistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/checklists': typeof AuthenticatedChecklistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/_authenticated/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/_authenticated/checklists/': typeof AuthenticatedChecklistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/painel'
    | '/validar/$token'
    | '/checklists/$id'
    | '/checklists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/painel'
    | '/validar/$token'
    | '/checklists/$id'
    | '/checklists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/painel'
    | '/validar/$token'
    | '/_authenticated/checklists/$id'
    | '/_authenticated/checklists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ValidarTokenRoute: typeof ValidarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$token': {
      id: '/validar/$token'
      path: '/validar/$token'
      fullPath: '/validar/$token'
      preLoaderRoute: typeof ValidarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists/': {
      id: '/_authenticated/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthenticatedChecklistsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists/$id': {
      id: '/_authenticated/checklists/$id'
      path: '/checklists/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof AuthenticatedChecklistsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedChecklistsIdRoute: typeof AuthenticatedChecklistsIdRoute
  AuthenticatedChecklistsIndexRoute: typeof AuthenticatedChecklistsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedChecklistsIdRoute: AuthenticatedChecklistsIdRoute,
  AuthenticatedChecklistsIndexRoute: AuthenticatedChecklistsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ValidarTokenRoute: ValidarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
