/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as CompletarCadastroRouteImport } from './routes/completar-cadastro'
import { Route as AutorizarAgentRouteImport } from './routes/autorizar-agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarTokenRouteImport } from './routes/validar.$token'
import { Route as ContraProvaTokenRouteImport } from './routes/contra-prova.$token'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTrocasOntRouteImport } from './routes/_authenticated/trocas-ont'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as AuthenticatedRemapeamentosRouteImport } from './routes/_authenticated/remapeamentos'
import { Route as AuthenticatedProvedorRouteImport } from './routes/_authenticated/provedor'
import { Route as AuthenticatedPlataformaRouteImport } from './routes/_authenticated/plataforma'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedIntervencoesRouteImport } from './routes/_authenticated/intervencoes'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedInformativosRouteImport } from './routes/_authenticated/informativos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCtosRouteImport } from './routes/_authenticated/ctos'
import { Route as AuthenticatedMapaOpticoIndexRouteImport } from './routes/_authenticated/mapa-optico.index'
import { Route as AuthenticatedChecklistsIndexRouteImport } from './routes/_authenticated/checklists.index'
import { Route as AuthenticatedAvaliacoesIndexRouteImport } from './routes/_authenticated/avaliacoes.index'
import { Route as AuthenticatedMapaOpticoCeoIdRouteImport } from './routes/_authenticated/mapa-optico.$ceoId'
import { Route as AuthenticatedChecklistsIdRouteImport } from './routes/_authenticated/checklists.$id'
import { Route as ApiPublicWebiDiagnosticUploadReportRouteImport } from './routes/api/public/webi-diagnostic/upload-report'
import { Route as ApiPublicWebiDiagnosticResolveChecklistRouteImport } from './routes/api/public/webi-diagnostic/resolve-checklist'
import { Route as ApiPublicWebiDiagnosticMyChecklistsRouteImport } from './routes/api/public/webi-diagnostic/my-checklists'
import { Route as ApiPublicWebiDiagnosticDeviceTokenRouteImport } from './routes/api/public/webi-diagnostic/device-token'
import { Route as ApiPublicWebiDiagnosticDeviceStartRouteImport } from './routes/api/public/webi-diagnostic/device-start'
import { Route as ApiPublicAuthLoginInternalRouteImport } from './routes/api/public/auth/login-internal'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarCadastroRoute = CompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizarAgentRoute = AutorizarAgentRouteImport.update({
  id: '/autorizar-agent',
  path: '/autorizar-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarTokenRoute = ValidarTokenRouteImport.update({
  id: '/validar/$token',
  path: '/validar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ContraProvaTokenRoute = ContraProvaTokenRouteImport.update({
  id: '/contra-prova/$token',
  path: '/contra-prova/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocasOntRoute = AuthenticatedTrocasOntRouteImport.update({
  id: '/trocas-ont',
  path: '/trocas-ont',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemapeamentosRoute =
  AuthenticatedRemapeamentosRouteImport.update({
    id: '/remapeamentos',
    path: '/remapeamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvedorRoute = AuthenticatedProvedorRouteImport.update({
  id: '/provedor',
  path: '/provedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlataformaRoute = AuthenticatedPlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntervencoesRoute =
  AuthenticatedIntervencoesRouteImport.update({
    id: '/intervencoes',
    path: '/intervencoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformativosRoute =
  AuthenticatedInformativosRouteImport.update({
    id: '/informativos',
    path: '/informativos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCtosRoute = AuthenticatedCtosRouteImport.update({
  id: '/ctos',
  path: '/ctos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaOpticoIndexRoute =
  AuthenticatedMapaOpticoIndexRouteImport.update({
    id: '/mapa-optico/',
    path: '/mapa-optico/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistsIndexRoute =
  AuthenticatedChecklistsIndexRouteImport.update({
    id: '/checklists/',
    path: '/checklists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvaliacoesIndexRoute =
  AuthenticatedAvaliacoesIndexRouteImport.update({
    id: '/avaliacoes/',
    path: '/avaliacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapaOpticoCeoIdRoute =
  AuthenticatedMapaOpticoCeoIdRouteImport.update({
    id: '/mapa-optico/$ceoId',
    path: '/mapa-optico/$ceoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistsIdRoute =
  AuthenticatedChecklistsIdRouteImport.update({
    id: '/checklists/$id',
    path: '/checklists/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebiDiagnosticUploadReportRoute =
  ApiPublicWebiDiagnosticUploadReportRouteImport.update({
    id: '/api/public/webi-diagnostic/upload-report',
    path: '/api/public/webi-diagnostic/upload-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebiDiagnosticResolveChecklistRoute =
  ApiPublicWebiDiagnosticResolveChecklistRouteImport.update({
    id: '/api/public/webi-diagnostic/resolve-checklist',
    path: '/api/public/webi-diagnostic/resolve-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebiDiagnosticMyChecklistsRoute =
  ApiPublicWebiDiagnosticMyChecklistsRouteImport.update({
    id: '/api/public/webi-diagnostic/my-checklists',
    path: '/api/public/webi-diagnostic/my-checklists',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebiDiagnosticDeviceTokenRoute =
  ApiPublicWebiDiagnosticDeviceTokenRouteImport.update({
    id: '/api/public/webi-diagnostic/device-token',
    path: '/api/public/webi-diagnostic/device-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebiDiagnosticDeviceStartRoute =
  ApiPublicWebiDiagnosticDeviceStartRouteImport.update({
    id: '/api/public/webi-diagnostic/device-start',
    path: '/api/public/webi-diagnostic/device-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthLoginInternalRoute =
  ApiPublicAuthLoginInternalRouteImport.update({
    id: '/api/public/auth/login-internal',
    path: '/api/public/auth/login-internal',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/autorizar-agent': typeof AutorizarAgentRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/ctos': typeof AuthenticatedCtosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/informativos': typeof AuthenticatedInformativosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/intervencoes': typeof AuthenticatedIntervencoesRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/plataforma': typeof AuthenticatedPlataformaRoute
  '/provedor': typeof AuthenticatedProvedorRoute
  '/remapeamentos': typeof AuthenticatedRemapeamentosRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/trocas-ont': typeof AuthenticatedTrocasOntRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/contra-prova/$token': typeof ContraProvaTokenRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/mapa-optico/$ceoId': typeof AuthenticatedMapaOpticoCeoIdRoute
  '/avaliacoes/': typeof AuthenticatedAvaliacoesIndexRoute
  '/checklists/': typeof AuthenticatedChecklistsIndexRoute
  '/mapa-optico/': typeof AuthenticatedMapaOpticoIndexRoute
  '/api/public/auth/login-internal': typeof ApiPublicAuthLoginInternalRoute
  '/api/public/webi-diagnostic/device-start': typeof ApiPublicWebiDiagnosticDeviceStartRoute
  '/api/public/webi-diagnostic/device-token': typeof ApiPublicWebiDiagnosticDeviceTokenRoute
  '/api/public/webi-diagnostic/my-checklists': typeof ApiPublicWebiDiagnosticMyChecklistsRoute
  '/api/public/webi-diagnostic/resolve-checklist': typeof ApiPublicWebiDiagnosticResolveChecklistRoute
  '/api/public/webi-diagnostic/upload-report': typeof ApiPublicWebiDiagnosticUploadReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/autorizar-agent': typeof AutorizarAgentRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/ctos': typeof AuthenticatedCtosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/informativos': typeof AuthenticatedInformativosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/intervencoes': typeof AuthenticatedIntervencoesRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/plataforma': typeof AuthenticatedPlataformaRoute
  '/provedor': typeof AuthenticatedProvedorRoute
  '/remapeamentos': typeof AuthenticatedRemapeamentosRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/trocas-ont': typeof AuthenticatedTrocasOntRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/contra-prova/$token': typeof ContraProvaTokenRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/mapa-optico/$ceoId': typeof AuthenticatedMapaOpticoCeoIdRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesIndexRoute
  '/checklists': typeof AuthenticatedChecklistsIndexRoute
  '/mapa-optico': typeof AuthenticatedMapaOpticoIndexRoute
  '/api/public/auth/login-internal': typeof ApiPublicAuthLoginInternalRoute
  '/api/public/webi-diagnostic/device-start': typeof ApiPublicWebiDiagnosticDeviceStartRoute
  '/api/public/webi-diagnostic/device-token': typeof ApiPublicWebiDiagnosticDeviceTokenRoute
  '/api/public/webi-diagnostic/my-checklists': typeof ApiPublicWebiDiagnosticMyChecklistsRoute
  '/api/public/webi-diagnostic/resolve-checklist': typeof ApiPublicWebiDiagnosticResolveChecklistRoute
  '/api/public/webi-diagnostic/upload-report': typeof ApiPublicWebiDiagnosticUploadReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/autorizar-agent': typeof AutorizarAgentRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_authenticated/ctos': typeof AuthenticatedCtosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/informativos': typeof AuthenticatedInformativosRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/intervencoes': typeof AuthenticatedIntervencoesRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/plataforma': typeof AuthenticatedPlataformaRoute
  '/_authenticated/provedor': typeof AuthenticatedProvedorRoute
  '/_authenticated/remapeamentos': typeof AuthenticatedRemapeamentosRoute
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRoute
  '/_authenticated/trocas-ont': typeof AuthenticatedTrocasOntRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/contra-prova/$token': typeof ContraProvaTokenRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/_authenticated/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/_authenticated/mapa-optico/$ceoId': typeof AuthenticatedMapaOpticoCeoIdRoute
  '/_authenticated/avaliacoes/': typeof AuthenticatedAvaliacoesIndexRoute
  '/_authenticated/checklists/': typeof AuthenticatedChecklistsIndexRoute
  '/_authenticated/mapa-optico/': typeof AuthenticatedMapaOpticoIndexRoute
  '/api/public/auth/login-internal': typeof ApiPublicAuthLoginInternalRoute
  '/api/public/webi-diagnostic/device-start': typeof ApiPublicWebiDiagnosticDeviceStartRoute
  '/api/public/webi-diagnostic/device-token': typeof ApiPublicWebiDiagnosticDeviceTokenRoute
  '/api/public/webi-diagnostic/my-checklists': typeof ApiPublicWebiDiagnosticMyChecklistsRoute
  '/api/public/webi-diagnostic/resolve-checklist': typeof ApiPublicWebiDiagnosticResolveChecklistRoute
  '/api/public/webi-diagnostic/upload-report': typeof ApiPublicWebiDiagnosticUploadReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/autorizar-agent'
    | '/completar-cadastro'
    | '/trocar-senha'
    | '/ctos'
    | '/dashboard'
    | '/informativos'
    | '/integracoes'
    | '/intervencoes'
    | '/minha-conta'
    | '/painel'
    | '/plataforma'
    | '/provedor'
    | '/remapeamentos'
    | '/seguranca'
    | '/trocas-ont'
    | '/usuarios'
    | '/contra-prova/$token'
    | '/validar/$token'
    | '/checklists/$id'
    | '/mapa-optico/$ceoId'
    | '/avaliacoes/'
    | '/checklists/'
    | '/mapa-optico/'
    | '/api/public/auth/login-internal'
    | '/api/public/webi-diagnostic/device-start'
    | '/api/public/webi-diagnostic/device-token'
    | '/api/public/webi-diagnostic/my-checklists'
    | '/api/public/webi-diagnostic/resolve-checklist'
    | '/api/public/webi-diagnostic/upload-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/autorizar-agent'
    | '/completar-cadastro'
    | '/trocar-senha'
    | '/ctos'
    | '/dashboard'
    | '/informativos'
    | '/integracoes'
    | '/intervencoes'
    | '/minha-conta'
    | '/painel'
    | '/plataforma'
    | '/provedor'
    | '/remapeamentos'
    | '/seguranca'
    | '/trocas-ont'
    | '/usuarios'
    | '/contra-prova/$token'
    | '/validar/$token'
    | '/checklists/$id'
    | '/mapa-optico/$ceoId'
    | '/avaliacoes'
    | '/checklists'
    | '/mapa-optico'
    | '/api/public/auth/login-internal'
    | '/api/public/webi-diagnostic/device-start'
    | '/api/public/webi-diagnostic/device-token'
    | '/api/public/webi-diagnostic/my-checklists'
    | '/api/public/webi-diagnostic/resolve-checklist'
    | '/api/public/webi-diagnostic/upload-report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/autorizar-agent'
    | '/completar-cadastro'
    | '/trocar-senha'
    | '/_authenticated/ctos'
    | '/_authenticated/dashboard'
    | '/_authenticated/informativos'
    | '/_authenticated/integracoes'
    | '/_authenticated/intervencoes'
    | '/_authenticated/minha-conta'
    | '/_authenticated/painel'
    | '/_authenticated/plataforma'
    | '/_authenticated/provedor'
    | '/_authenticated/remapeamentos'
    | '/_authenticated/seguranca'
    | '/_authenticated/trocas-ont'
    | '/_authenticated/usuarios'
    | '/contra-prova/$token'
    | '/validar/$token'
    | '/_authenticated/checklists/$id'
    | '/_authenticated/mapa-optico/$ceoId'
    | '/_authenticated/avaliacoes/'
    | '/_authenticated/checklists/'
    | '/_authenticated/mapa-optico/'
    | '/api/public/auth/login-internal'
    | '/api/public/webi-diagnostic/device-start'
    | '/api/public/webi-diagnostic/device-token'
    | '/api/public/webi-diagnostic/my-checklists'
    | '/api/public/webi-diagnostic/resolve-checklist'
    | '/api/public/webi-diagnostic/upload-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AutorizarAgentRoute: typeof AutorizarAgentRoute
  CompletarCadastroRoute: typeof CompletarCadastroRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  ContraProvaTokenRoute: typeof ContraProvaTokenRoute
  ValidarTokenRoute: typeof ValidarTokenRoute
  ApiPublicAuthLoginInternalRoute: typeof ApiPublicAuthLoginInternalRoute
  ApiPublicWebiDiagnosticDeviceStartRoute: typeof ApiPublicWebiDiagnosticDeviceStartRoute
  ApiPublicWebiDiagnosticDeviceTokenRoute: typeof ApiPublicWebiDiagnosticDeviceTokenRoute
  ApiPublicWebiDiagnosticMyChecklistsRoute: typeof ApiPublicWebiDiagnosticMyChecklistsRoute
  ApiPublicWebiDiagnosticResolveChecklistRoute: typeof ApiPublicWebiDiagnosticResolveChecklistRoute
  ApiPublicWebiDiagnosticUploadReportRoute: typeof ApiPublicWebiDiagnosticUploadReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-cadastro': {
      id: '/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof CompletarCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizar-agent': {
      id: '/autorizar-agent'
      path: '/autorizar-agent'
      fullPath: '/autorizar-agent'
      preLoaderRoute: typeof AutorizarAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$token': {
      id: '/validar/$token'
      path: '/validar/$token'
      fullPath: '/validar/$token'
      preLoaderRoute: typeof ValidarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contra-prova/$token': {
      id: '/contra-prova/$token'
      path: '/contra-prova/$token'
      fullPath: '/contra-prova/$token'
      preLoaderRoute: typeof ContraProvaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocas-ont': {
      id: '/_authenticated/trocas-ont'
      path: '/trocas-ont'
      fullPath: '/trocas-ont'
      preLoaderRoute: typeof AuthenticatedTrocasOntRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remapeamentos': {
      id: '/_authenticated/remapeamentos'
      path: '/remapeamentos'
      fullPath: '/remapeamentos'
      preLoaderRoute: typeof AuthenticatedRemapeamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provedor': {
      id: '/_authenticated/provedor'
      path: '/provedor'
      fullPath: '/provedor'
      preLoaderRoute: typeof AuthenticatedProvedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plataforma': {
      id: '/_authenticated/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof AuthenticatedPlataformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intervencoes': {
      id: '/_authenticated/intervencoes'
      path: '/intervencoes'
      fullPath: '/intervencoes'
      preLoaderRoute: typeof AuthenticatedIntervencoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informativos': {
      id: '/_authenticated/informativos'
      path: '/informativos'
      fullPath: '/informativos'
      preLoaderRoute: typeof AuthenticatedInformativosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ctos': {
      id: '/_authenticated/ctos'
      path: '/ctos'
      fullPath: '/ctos'
      preLoaderRoute: typeof AuthenticatedCtosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa-optico/': {
      id: '/_authenticated/mapa-optico/'
      path: '/mapa-optico'
      fullPath: '/mapa-optico/'
      preLoaderRoute: typeof AuthenticatedMapaOpticoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists/': {
      id: '/_authenticated/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthenticatedChecklistsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes/': {
      id: '/_authenticated/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/avaliacoes/'
      preLoaderRoute: typeof AuthenticatedAvaliacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa-optico/$ceoId': {
      id: '/_authenticated/mapa-optico/$ceoId'
      path: '/mapa-optico/$ceoId'
      fullPath: '/mapa-optico/$ceoId'
      preLoaderRoute: typeof AuthenticatedMapaOpticoCeoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists/$id': {
      id: '/_authenticated/checklists/$id'
      path: '/checklists/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof AuthenticatedChecklistsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webi-diagnostic/upload-report': {
      id: '/api/public/webi-diagnostic/upload-report'
      path: '/api/public/webi-diagnostic/upload-report'
      fullPath: '/api/public/webi-diagnostic/upload-report'
      preLoaderRoute: typeof ApiPublicWebiDiagnosticUploadReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webi-diagnostic/resolve-checklist': {
      id: '/api/public/webi-diagnostic/resolve-checklist'
      path: '/api/public/webi-diagnostic/resolve-checklist'
      fullPath: '/api/public/webi-diagnostic/resolve-checklist'
      preLoaderRoute: typeof ApiPublicWebiDiagnosticResolveChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webi-diagnostic/my-checklists': {
      id: '/api/public/webi-diagnostic/my-checklists'
      path: '/api/public/webi-diagnostic/my-checklists'
      fullPath: '/api/public/webi-diagnostic/my-checklists'
      preLoaderRoute: typeof ApiPublicWebiDiagnosticMyChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webi-diagnostic/device-token': {
      id: '/api/public/webi-diagnostic/device-token'
      path: '/api/public/webi-diagnostic/device-token'
      fullPath: '/api/public/webi-diagnostic/device-token'
      preLoaderRoute: typeof ApiPublicWebiDiagnosticDeviceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webi-diagnostic/device-start': {
      id: '/api/public/webi-diagnostic/device-start'
      path: '/api/public/webi-diagnostic/device-start'
      fullPath: '/api/public/webi-diagnostic/device-start'
      preLoaderRoute: typeof ApiPublicWebiDiagnosticDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/login-internal': {
      id: '/api/public/auth/login-internal'
      path: '/api/public/auth/login-internal'
      fullPath: '/api/public/auth/login-internal'
      preLoaderRoute: typeof ApiPublicAuthLoginInternalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCtosRoute: typeof AuthenticatedCtosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInformativosRoute: typeof AuthenticatedInformativosRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedIntervencoesRoute: typeof AuthenticatedIntervencoesRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPlataformaRoute: typeof AuthenticatedPlataformaRoute
  AuthenticatedProvedorRoute: typeof AuthenticatedProvedorRoute
  AuthenticatedRemapeamentosRoute: typeof AuthenticatedRemapeamentosRoute
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRoute
  AuthenticatedTrocasOntRoute: typeof AuthenticatedTrocasOntRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedChecklistsIdRoute: typeof AuthenticatedChecklistsIdRoute
  AuthenticatedMapaOpticoCeoIdRoute: typeof AuthenticatedMapaOpticoCeoIdRoute
  AuthenticatedAvaliacoesIndexRoute: typeof AuthenticatedAvaliacoesIndexRoute
  AuthenticatedChecklistsIndexRoute: typeof AuthenticatedChecklistsIndexRoute
  AuthenticatedMapaOpticoIndexRoute: typeof AuthenticatedMapaOpticoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCtosRoute: AuthenticatedCtosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInformativosRoute: AuthenticatedInformativosRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedIntervencoesRoute: AuthenticatedIntervencoesRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPlataformaRoute: AuthenticatedPlataformaRoute,
  AuthenticatedProvedorRoute: AuthenticatedProvedorRoute,
  AuthenticatedRemapeamentosRoute: AuthenticatedRemapeamentosRoute,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRoute,
  AuthenticatedTrocasOntRoute: AuthenticatedTrocasOntRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedChecklistsIdRoute: AuthenticatedChecklistsIdRoute,
  AuthenticatedMapaOpticoCeoIdRoute: AuthenticatedMapaOpticoCeoIdRoute,
  AuthenticatedAvaliacoesIndexRoute: AuthenticatedAvaliacoesIndexRoute,
  AuthenticatedChecklistsIndexRoute: AuthenticatedChecklistsIndexRoute,
  AuthenticatedMapaOpticoIndexRoute: AuthenticatedMapaOpticoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AutorizarAgentRoute: AutorizarAgentRoute,
  CompletarCadastroRoute: CompletarCadastroRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  ContraProvaTokenRoute: ContraProvaTokenRoute,
  ValidarTokenRoute: ValidarTokenRoute,
  ApiPublicAuthLoginInternalRoute: ApiPublicAuthLoginInternalRoute,
  ApiPublicWebiDiagnosticDeviceStartRoute:
    ApiPublicWebiDiagnosticDeviceStartRoute,
  ApiPublicWebiDiagnosticDeviceTokenRoute:
    ApiPublicWebiDiagnosticDeviceTokenRoute,
  ApiPublicWebiDiagnosticMyChecklistsRoute:
    ApiPublicWebiDiagnosticMyChecklistsRoute,
  ApiPublicWebiDiagnosticResolveChecklistRoute:
    ApiPublicWebiDiagnosticResolveChecklistRoute,
  ApiPublicWebiDiagnosticUploadReportRoute:
    ApiPublicWebiDiagnosticUploadReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
