/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompletarCadastroRouteImport } from './routes/completar-cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarTokenRouteImport } from './routes/validar.$token'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChecklistsIndexRouteImport } from './routes/_authenticated/checklists.index'
import { Route as AuthenticatedChecklistsIdRouteImport } from './routes/_authenticated/checklists.$id'
import { Route as ApiPublicWebiDiagnosticUploadReportRouteImport } from './routes/api/public/webi-diagnostic/upload-report'
import { Route as ApiPublicWebiDiagnosticResolveChecklistRouteImport } from './routes/api/public/webi-diagnostic/resolve-checklist'

const CompletarCadastroRoute = CompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarTokenRoute = ValidarTokenRouteImport.update({
  id: '/validar/$token',
  path: '/validar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistsIndexRoute =
  AuthenticatedChecklistsIndexRouteImport.update({
    id: '/checklists/',
    path: '/checklists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistsIdRoute =
  AuthenticatedChecklistsIdRouteImport.update({
    id: '/checklists/$id',
    path: '/checklists/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebiDiagnosticUploadReportRoute =
  ApiPublicWebiDiagnosticUploadReportRouteImport.update({
    id: '/api/public/webi-diagnostic/upload-report',
    path: '/api/public/webi-diagnostic/upload-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebiDiagnosticResolveChecklistRoute =
  ApiPublicWebiDiagnosticResolveChecklistRouteImport.update({
    id: '/api/public/webi-diagnostic/resolve-checklist',
    path: '/api/public/webi-diagnostic/resolve-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/checklists/': typeof AuthenticatedChecklistsIndexRoute
  '/api/public/webi-diagnostic/resolve-checklist': typeof ApiPublicWebiDiagnosticResolveChecklistRoute
  '/api/public/webi-diagnostic/upload-report': typeof ApiPublicWebiDiagnosticUploadReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/checklists': typeof AuthenticatedChecklistsIndexRoute
  '/api/public/webi-diagnostic/resolve-checklist': typeof ApiPublicWebiDiagnosticResolveChecklistRoute
  '/api/public/webi-diagnostic/upload-report': typeof ApiPublicWebiDiagnosticUploadReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/validar/$token': typeof ValidarTokenRoute
  '/_authenticated/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/_authenticated/checklists/': typeof AuthenticatedChecklistsIndexRoute
  '/api/public/webi-diagnostic/resolve-checklist': typeof ApiPublicWebiDiagnosticResolveChecklistRoute
  '/api/public/webi-diagnostic/upload-report': typeof ApiPublicWebiDiagnosticUploadReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/completar-cadastro'
    | '/dashboard'
    | '/integracoes'
    | '/painel'
    | '/usuarios'
    | '/validar/$token'
    | '/checklists/$id'
    | '/checklists/'
    | '/api/public/webi-diagnostic/resolve-checklist'
    | '/api/public/webi-diagnostic/upload-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/completar-cadastro'
    | '/dashboard'
    | '/integracoes'
    | '/painel'
    | '/usuarios'
    | '/validar/$token'
    | '/checklists/$id'
    | '/checklists'
    | '/api/public/webi-diagnostic/resolve-checklist'
    | '/api/public/webi-diagnostic/upload-report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/completar-cadastro'
    | '/_authenticated/dashboard'
    | '/_authenticated/integracoes'
    | '/_authenticated/painel'
    | '/_authenticated/usuarios'
    | '/validar/$token'
    | '/_authenticated/checklists/$id'
    | '/_authenticated/checklists/'
    | '/api/public/webi-diagnostic/resolve-checklist'
    | '/api/public/webi-diagnostic/upload-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompletarCadastroRoute: typeof CompletarCadastroRoute
  ValidarTokenRoute: typeof ValidarTokenRoute
  ApiPublicWebiDiagnosticResolveChecklistRoute: typeof ApiPublicWebiDiagnosticResolveChecklistRoute
  ApiPublicWebiDiagnosticUploadReportRoute: typeof ApiPublicWebiDiagnosticUploadReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/completar-cadastro': {
      id: '/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof CompletarCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$token': {
      id: '/validar/$token'
      path: '/validar/$token'
      fullPath: '/validar/$token'
      preLoaderRoute: typeof ValidarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists/': {
      id: '/_authenticated/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthenticatedChecklistsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists/$id': {
      id: '/_authenticated/checklists/$id'
      path: '/checklists/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof AuthenticatedChecklistsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webi-diagnostic/upload-report': {
      id: '/api/public/webi-diagnostic/upload-report'
      path: '/api/public/webi-diagnostic/upload-report'
      fullPath: '/api/public/webi-diagnostic/upload-report'
      preLoaderRoute: typeof ApiPublicWebiDiagnosticUploadReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webi-diagnostic/resolve-checklist': {
      id: '/api/public/webi-diagnostic/resolve-checklist'
      path: '/api/public/webi-diagnostic/resolve-checklist'
      fullPath: '/api/public/webi-diagnostic/resolve-checklist'
      preLoaderRoute: typeof ApiPublicWebiDiagnosticResolveChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedChecklistsIdRoute: typeof AuthenticatedChecklistsIdRoute
  AuthenticatedChecklistsIndexRoute: typeof AuthenticatedChecklistsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedChecklistsIdRoute: AuthenticatedChecklistsIdRoute,
  AuthenticatedChecklistsIndexRoute: AuthenticatedChecklistsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompletarCadastroRoute: CompletarCadastroRoute,
  ValidarTokenRoute: ValidarTokenRoute,
  ApiPublicWebiDiagnosticResolveChecklistRoute:
    ApiPublicWebiDiagnosticResolveChecklistRoute,
  ApiPublicWebiDiagnosticUploadReportRoute:
    ApiPublicWebiDiagnosticUploadReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
