-- WebiCheck — Diagnóstico Inteligente + Webi NOC IA V1
-- Migration aditiva e isolada. Não altera checklists, revisões ou documentos existentes.

CREATE TABLE IF NOT EXISTS public.smart_diagnostic_settings (
  provider_id uuid PRIMARY KEY REFERENCES public.providers(id) ON DELETE CASCADE,
  optical_rx_min_dbm numeric,
  optical_rx_max_dbm numeric,
  noc_whatsapp_e164 text,
  ai_enabled boolean NOT NULL DEFAULT false,
  learning_enabled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    optical_rx_min_dbm IS NULL
    OR optical_rx_max_dbm IS NULL
    OR optical_rx_min_dbm < optical_rx_max_dbm
  ),
  CHECK (noc_whatsapp_e164 IS NULL OR noc_whatsapp_e164 ~ '^55[1-9][0-9]{9,10}$')
);

CREATE TABLE IF NOT EXISTS public.smart_diagnostic_sessions (
  id uuid PRIMARY KEY,
  provider_id uuid NOT NULL REFERENCES public.providers(id) ON DELETE RESTRICT,
  technician_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  checklist_id uuid REFERENCES public.checklists(id) ON DELETE SET NULL,
  case_id uuid,
  checklist_code text,
  service_order text,
  client_name text,
  city text,
  service_type text NOT NULL DEFAULT 'manutencao'
    CHECK (service_type IN ('manutencao')),
  equipment_model text,
  engine_version text NOT NULL,
  status text NOT NULL,
  symptom_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  answers_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  deterministic_evaluation jsonb NOT NULL DEFAULT '{}'::jsonb,
  decision_path jsonb NOT NULL DEFAULT '[]'::jsonb,
  validated_for_learning boolean NOT NULL DEFAULT false,
  validated_by uuid REFERENCES auth.users(id) ON DELETE RESTRICT,
  validated_at timestamptz,
  started_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_provider_updated
  ON public.smart_diagnostic_sessions(provider_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_technician_updated
  ON public.smart_diagnostic_sessions(technician_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_checklist
  ON public.smart_diagnostic_sessions(checklist_id, updated_at DESC)
  WHERE checklist_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_case
  ON public.smart_diagnostic_sessions(case_id, updated_at DESC)
  WHERE case_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.smart_diagnostic_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.smart_diagnostic_sessions(id) ON DELETE RESTRICT,
  client_event_id uuid NOT NULL,
  question_id text NOT NULL,
  question_text text NOT NULL,
  category text NOT NULL,
  answer jsonb NOT NULL,
  answer_label text NOT NULL,
  evidence_label text,
  origin text NOT NULL CHECK (origin IN ('technician','webi-diagnostic','system')),
  engine_version text NOT NULL,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  event_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, client_event_id)
);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_events_session
  ON public.smart_diagnostic_events(session_id, event_at);

CREATE TABLE IF NOT EXISTS public.smart_diagnostic_measurements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.smart_diagnostic_sessions(id) ON DELETE RESTRICT,
  metric_key text NOT NULL,
  numeric_value numeric,
  text_value text,
  unit text,
  source text NOT NULL DEFAULT 'technician',
  measured_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (session_id, metric_key),
  CHECK (numeric_value IS NOT NULL OR text_value IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_measurements_session
  ON public.smart_diagnostic_measurements(session_id, measured_at);

CREATE TABLE IF NOT EXISTS public.smart_diagnostic_evidence (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES public.smart_diagnostic_sessions(id) ON DELETE RESTRICT,
  event_id bigint REFERENCES public.smart_diagnostic_events(id) ON DELETE RESTRICT,
  evidence_type text NOT NULL,
  storage_path text,
  external_reference text,
  sha256 text,
  source text NOT NULL DEFAULT 'technician',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  recorded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CHECK (storage_path IS NOT NULL OR external_reference IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_evidence_session
  ON public.smart_diagnostic_evidence(session_id, recorded_at);

CREATE TABLE IF NOT EXISTS public.smart_diagnostic_ai_reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES public.smart_diagnostic_sessions(id) ON DELETE RESTRICT,
  mode text NOT NULL CHECK (mode IN ('triage','review')),
  model text NOT NULL,
  prompt_version text NOT NULL,
  structured_input jsonb NOT NULL,
  structured_output jsonb NOT NULL,
  deterministic_status text NOT NULL,
  guardrails_applied jsonb NOT NULL DEFAULT '[]'::jsonb,
  request_id text,
  input_tokens integer,
  output_tokens integer,
  analyzed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  analyzed_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_ai_reviews_session
  ON public.smart_diagnostic_ai_reviews(session_id, analyzed_at DESC);

CREATE TABLE IF NOT EXISTS public.smart_diagnostic_learning_cases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL UNIQUE REFERENCES public.smart_diagnostic_sessions(id) ON DELETE RESTRICT,
  provider_id uuid NOT NULL REFERENCES public.providers(id) ON DELETE RESTRICT,
  symptom_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  equipment_model text,
  probable_cause text NOT NULL,
  outcome text NOT NULL,
  technical_summary text NOT NULL,
  embedding_model text,
  embedding_json jsonb,
  validated_for_learning boolean NOT NULL DEFAULT false,
  validated_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  validated_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_learning_provider
  ON public.smart_diagnostic_learning_cases(provider_id, validated_at DESC)
  WHERE validated_for_learning IS TRUE;

CREATE OR REPLACE FUNCTION public.protect_validated_smart_diagnostic()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF OLD.validated_for_learning IS TRUE THEN
    RAISE EXCEPTION 'smart_diagnostic_validated_snapshot_immutable';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_validated_smart_diagnostic
  ON public.smart_diagnostic_sessions;
CREATE TRIGGER trg_protect_validated_smart_diagnostic
BEFORE UPDATE ON public.smart_diagnostic_sessions
FOR EACH ROW
WHEN (OLD.validated_for_learning IS TRUE)
EXECUTE FUNCTION public.protect_validated_smart_diagnostic();

ALTER TABLE public.smart_diagnostic_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_diagnostic_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_diagnostic_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_diagnostic_measurements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_diagnostic_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_diagnostic_ai_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_diagnostic_learning_cases ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON
  public.smart_diagnostic_settings,
  public.smart_diagnostic_sessions,
  public.smart_diagnostic_events,
  public.smart_diagnostic_measurements,
  public.smart_diagnostic_evidence,
  public.smart_diagnostic_ai_reviews,
  public.smart_diagnostic_learning_cases
FROM PUBLIC, anon;

GRANT SELECT, INSERT, UPDATE ON public.smart_diagnostic_sessions TO authenticated;
GRANT SELECT, INSERT ON
  public.smart_diagnostic_events,
  public.smart_diagnostic_evidence,
  public.smart_diagnostic_ai_reviews
TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.smart_diagnostic_measurements TO authenticated;
GRANT SELECT ON public.smart_diagnostic_settings, public.smart_diagnostic_learning_cases
TO authenticated;
GRANT INSERT, UPDATE ON public.smart_diagnostic_learning_cases TO authenticated;
GRANT ALL ON
  public.smart_diagnostic_settings,
  public.smart_diagnostic_sessions,
  public.smart_diagnostic_events,
  public.smart_diagnostic_measurements,
  public.smart_diagnostic_evidence,
  public.smart_diagnostic_ai_reviews,
  public.smart_diagnostic_learning_cases
TO service_role;
GRANT USAGE, SELECT ON SEQUENCE
  public.smart_diagnostic_events_id_seq,
  public.smart_diagnostic_measurements_id_seq
TO authenticated, service_role;

DROP POLICY IF EXISTS smart_diagnostic_settings_read ON public.smart_diagnostic_settings;
CREATE POLICY smart_diagnostic_settings_read
ON public.smart_diagnostic_settings FOR SELECT TO authenticated
USING (provider_id = public.current_provider_id());

DROP POLICY IF EXISTS smart_diagnostic_sessions_read ON public.smart_diagnostic_sessions;
CREATE POLICY smart_diagnostic_sessions_read
ON public.smart_diagnostic_sessions FOR SELECT TO authenticated
USING (
  provider_id = public.current_provider_id()
  AND (technician_id = auth.uid() OR public.has_role(auth.uid(), 'admin'))
);

DROP POLICY IF EXISTS smart_diagnostic_sessions_insert ON public.smart_diagnostic_sessions;
CREATE POLICY smart_diagnostic_sessions_insert
ON public.smart_diagnostic_sessions FOR INSERT TO authenticated
WITH CHECK (
  provider_id = public.current_provider_id()
  AND technician_id = auth.uid()
);

DROP POLICY IF EXISTS smart_diagnostic_sessions_update ON public.smart_diagnostic_sessions;
CREATE POLICY smart_diagnostic_sessions_update
ON public.smart_diagnostic_sessions FOR UPDATE TO authenticated
USING (
  provider_id = public.current_provider_id()
  AND (technician_id = auth.uid() OR public.has_role(auth.uid(), 'admin'))
)
WITH CHECK (provider_id = public.current_provider_id());

DROP POLICY IF EXISTS smart_diagnostic_events_read ON public.smart_diagnostic_events;
CREATE POLICY smart_diagnostic_events_read
ON public.smart_diagnostic_events FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND (s.technician_id = auth.uid() OR public.has_role(auth.uid(), 'admin'))
  )
);

DROP POLICY IF EXISTS smart_diagnostic_events_insert ON public.smart_diagnostic_events;
CREATE POLICY smart_diagnostic_events_insert
ON public.smart_diagnostic_events FOR INSERT TO authenticated
WITH CHECK (
  actor_user_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND s.technician_id = auth.uid()
  )
);

DROP POLICY IF EXISTS smart_diagnostic_measurements_read
  ON public.smart_diagnostic_measurements;
CREATE POLICY smart_diagnostic_measurements_read
ON public.smart_diagnostic_measurements FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND (s.technician_id = auth.uid() OR public.has_role(auth.uid(), 'admin'))
  )
);

DROP POLICY IF EXISTS smart_diagnostic_measurements_insert
  ON public.smart_diagnostic_measurements;
CREATE POLICY smart_diagnostic_measurements_insert
ON public.smart_diagnostic_measurements FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND s.technician_id = auth.uid()
  )
);

DROP POLICY IF EXISTS smart_diagnostic_measurements_update
  ON public.smart_diagnostic_measurements;
CREATE POLICY smart_diagnostic_measurements_update
ON public.smart_diagnostic_measurements FOR UPDATE TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND s.technician_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND s.technician_id = auth.uid()
  )
);

DROP POLICY IF EXISTS smart_diagnostic_evidence_read ON public.smart_diagnostic_evidence;
CREATE POLICY smart_diagnostic_evidence_read
ON public.smart_diagnostic_evidence FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND (s.technician_id = auth.uid() OR public.has_role(auth.uid(), 'admin'))
  )
);

DROP POLICY IF EXISTS smart_diagnostic_evidence_insert ON public.smart_diagnostic_evidence;
CREATE POLICY smart_diagnostic_evidence_insert
ON public.smart_diagnostic_evidence FOR INSERT TO authenticated
WITH CHECK (
  recorded_by = auth.uid()
  AND EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND s.technician_id = auth.uid()
  )
);

DROP POLICY IF EXISTS smart_diagnostic_ai_reviews_read ON public.smart_diagnostic_ai_reviews;
CREATE POLICY smart_diagnostic_ai_reviews_read
ON public.smart_diagnostic_ai_reviews FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND (s.technician_id = auth.uid() OR public.has_role(auth.uid(), 'admin'))
  )
);

DROP POLICY IF EXISTS smart_diagnostic_ai_reviews_insert ON public.smart_diagnostic_ai_reviews;
CREATE POLICY smart_diagnostic_ai_reviews_insert
ON public.smart_diagnostic_ai_reviews FOR INSERT TO authenticated
WITH CHECK (
  analyzed_by = auth.uid()
  AND EXISTS (
    SELECT 1 FROM public.smart_diagnostic_sessions s
    WHERE s.id = session_id
      AND s.provider_id = public.current_provider_id()
      AND s.technician_id = auth.uid()
  )
);

DROP POLICY IF EXISTS smart_diagnostic_learning_read
  ON public.smart_diagnostic_learning_cases;
CREATE POLICY smart_diagnostic_learning_read
ON public.smart_diagnostic_learning_cases FOR SELECT TO authenticated
USING (
  provider_id = public.current_provider_id()
  AND validated_for_learning IS TRUE
);

DROP POLICY IF EXISTS smart_diagnostic_learning_admin_insert
  ON public.smart_diagnostic_learning_cases;
CREATE POLICY smart_diagnostic_learning_admin_insert
ON public.smart_diagnostic_learning_cases FOR INSERT TO authenticated
WITH CHECK (
  provider_id = public.current_provider_id()
  AND validated_by = auth.uid()
  AND public.has_role(auth.uid(), 'admin')
);

DROP POLICY IF EXISTS smart_diagnostic_learning_admin_update
  ON public.smart_diagnostic_learning_cases;
CREATE POLICY smart_diagnostic_learning_admin_update
ON public.smart_diagnostic_learning_cases FOR UPDATE TO authenticated
USING (
  provider_id = public.current_provider_id()
  AND public.has_role(auth.uid(), 'admin')
)
WITH CHECK (provider_id = public.current_provider_id());

INSERT INTO storage.buckets (id, name, public)
VALUES ('smart-diagnostic-evidence', 'smart-diagnostic-evidence', false)
ON CONFLICT (id) DO NOTHING;
