-- WebiCheck — Diagnóstico operacional, AI Gateway e contra-prova de manutenção.
-- Aditiva: não remove nem reescreve dados existentes.

ALTER TABLE public.smart_diagnostic_sessions
  ADD COLUMN IF NOT EXISTS root_session_id uuid,
  ADD COLUMN IF NOT EXISTS parent_session_id uuid,
  ADD COLUMN IF NOT EXISTS revision_number integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS revision_reason text,
  ADD COLUMN IF NOT EXISTS metadata_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS operation_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS location_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS server_started_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS finalized_at timestamptz;

UPDATE public.smart_diagnostic_sessions
SET root_session_id = id
WHERE root_session_id IS NULL;

ALTER TABLE public.smart_diagnostic_sessions
  ALTER COLUMN root_session_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_smart_diagnostic_revision
  ON public.smart_diagnostic_sessions(root_session_id, revision_number);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_parent_session
  ON public.smart_diagnostic_sessions(parent_session_id)
  WHERE parent_session_id IS NOT NULL;

ALTER TABLE public.smart_diagnostic_ai_reviews
  ADD COLUMN IF NOT EXISTS provider text,
  ADD COLUMN IF NOT EXISTS latency_ms integer,
  ADD COLUMN IF NOT EXISTS total_tokens integer,
  ADD COLUMN IF NOT EXISTS estimated_cost numeric,
  ADD COLUMN IF NOT EXISTS fallback_used boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS fallback_reason text,
  ADD COLUMN IF NOT EXISTS error_code text;

CREATE TABLE IF NOT EXISTS public.smart_diagnostic_ai_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id uuid NOT NULL REFERENCES public.providers(id) ON DELETE RESTRICT,
  session_id uuid REFERENCES public.smart_diagnostic_sessions(id) ON DELETE SET NULL,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  provider text NOT NULL,
  model text NOT NULL,
  operation text NOT NULL,
  latency_ms integer,
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  estimated_cost numeric,
  success boolean NOT NULL,
  fallback_used boolean NOT NULL DEFAULT false,
  fallback_reason text,
  error_code text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_ai_usage_provider_created
  ON public.smart_diagnostic_ai_usage(provider_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_smart_diagnostic_ai_usage_session
  ON public.smart_diagnostic_ai_usage(session_id, created_at DESC)
  WHERE session_id IS NOT NULL;

ALTER TABLE public.smart_diagnostic_ai_usage ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.smart_diagnostic_ai_usage FROM PUBLIC, anon;
GRANT SELECT ON public.smart_diagnostic_ai_usage TO authenticated;
GRANT ALL ON public.smart_diagnostic_ai_usage TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.smart_diagnostic_ai_usage_id_seq TO authenticated, service_role;

DROP POLICY IF EXISTS smart_diagnostic_ai_usage_admin_read ON public.smart_diagnostic_ai_usage;
CREATE POLICY smart_diagnostic_ai_usage_admin_read
ON public.smart_diagnostic_ai_usage FOR SELECT TO authenticated
USING (provider_id = public.current_provider_id() AND public.has_role(auth.uid(), 'admin'));

ALTER TABLE public.customer_counterproofs
  ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'installation'
    CHECK (kind IN ('installation', 'maintenance')),
  ADD COLUMN IF NOT EXISTS diagnostic_session_id uuid
    REFERENCES public.smart_diagnostic_sessions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS diagnostic_context jsonb NOT NULL DEFAULT '{}'::jsonb;

DROP INDEX IF EXISTS public.uq_counterproof_one_active_per_checklist;
CREATE UNIQUE INDEX IF NOT EXISTS uq_counterproof_one_active_per_checklist_kind
  ON public.customer_counterproofs(checklist_id, kind)
  WHERE status IN ('pending', 'opened', 'validated');
CREATE UNIQUE INDEX IF NOT EXISTS uq_counterproof_one_active_per_diagnostic
  ON public.customer_counterproofs(diagnostic_session_id)
  WHERE diagnostic_session_id IS NOT NULL AND status IN ('pending', 'opened', 'validated');
CREATE INDEX IF NOT EXISTS idx_counterproof_diagnostic
  ON public.customer_counterproofs(diagnostic_session_id, created_at DESC)
  WHERE diagnostic_session_id IS NOT NULL;
